version: '3'
services:
  app:
    build: 
        context: .
    restart: always
    depends_on:
      - mongo
    ports:
      - '5050:3000'
    env_file:
      - .env
  mongo:
   image: mongo
   restart: always
  #  volumes:
  #    - ./data:/data/db
   ports:
      - 27018:27017
