version: '3'
services:
  app:
    build: 
        context: .
    restart: always
    ports:
      - '5050:4000'
    env_file:
      - .env
  mongo:
   image: mongo
   restart: always
   volumes:
     - ./postgresqldata:/var/lib/postgresql/data
   ports:
      - 27018:27017
networks:
 default:
  external:
   name: prod
