version: '3'
services:
  mongo:
    container_name: app_db
    image: mongo
    restart: always    
    ports:
      - '27018:27017'
    environment:
      -  'MONGO_INITDB_ROOT_USERNAME: root'
      -  'MONGO_INITDB_ROOT_PASSWORD: root@1517'
  app:
    container_name: run_app
    restart: always
    build: .
    ports:
      - '3000:3000'
    env_file:
      - .env
    depends_on:
      - mongo
