kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-db-mongodb-tusecreto
spec:
  storageClassName: nfs-client
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi