apiVersion: v1
kind: Service
metadata:
  name: tusecreto-mongodb
  labels:
    app: tusecreto-mongodb
spec:
  type: ClusterIP
  selector:
    app: tusecreto-mongodb
  ports:
  - port: 27017
    targetPort: 27017